# TCL File Generated by Component Editor 18.1
# Mon May 13 16:32:42 EDT 2019
# DO NOT MODIFY


# 
# rasterizer_unit "rasterizer_unit" v1.0
#  2019.05.13.16:32:42
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module rasterizer_unit
# 
set_module_property DESCRIPTION ""
set_module_property NAME rasterizer_unit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME rasterizer_unit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL rasterizer_unit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file fifo.sv SYSTEM_VERILOG PATH fifo.sv
add_fileset_file rasterizer.sv SYSTEM_VERILOG PATH rasterizer.sv
add_fileset_file rasterizer_fetch_logic.sv SYSTEM_VERILOG PATH rasterizer_fetch_logic.sv
add_fileset_file rasterizer_unit.sv SYSTEM_VERILOG PATH rasterizer_unit.sv TOP_LEVEL_FILE
add_fileset_file rasterizer_vertex_fetch.sv SYSTEM_VERILOG PATH rasterizer_vertex_fetch.sv
add_fileset_file vertex_calc.sv SYSTEM_VERILOG PATH vertex_calc.sv
add_fileset_file ztest.sv SYSTEM_VERILOG PATH ztest.sv
add_fileset_file config_reg.sv SYSTEM_VERILOG PATH config_reg.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_address address Output 26
add_interface_port avalon_master master_byteenable byteenable Output 4
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_readdata readdata Input 32
add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output 32


# 
# connection point avalon_master_1
# 
add_interface avalon_master_1 avalon start
set_interface_property avalon_master_1 addressUnits SYMBOLS
set_interface_property avalon_master_1 associatedClock clock
set_interface_property avalon_master_1 associatedReset reset
set_interface_property avalon_master_1 bitsPerSymbol 8
set_interface_property avalon_master_1 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_1 burstcountUnits WORDS
set_interface_property avalon_master_1 doStreamReads false
set_interface_property avalon_master_1 doStreamWrites false
set_interface_property avalon_master_1 holdTime 0
set_interface_property avalon_master_1 linewrapBursts false
set_interface_property avalon_master_1 maximumPendingReadTransactions 0
set_interface_property avalon_master_1 maximumPendingWriteTransactions 0
set_interface_property avalon_master_1 readLatency 0
set_interface_property avalon_master_1 readWaitTime 1
set_interface_property avalon_master_1 setupTime 0
set_interface_property avalon_master_1 timingUnits Cycles
set_interface_property avalon_master_1 writeWaitTime 0
set_interface_property avalon_master_1 ENABLED true
set_interface_property avalon_master_1 EXPORT_OF ""
set_interface_property avalon_master_1 PORT_NAME_MAP ""
set_interface_property avalon_master_1 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_1 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_1 master_address_2 address Output 26
add_interface_port avalon_master_1 master_read_2 read Output 1
add_interface_port avalon_master_1 master_write_2 write Output 1
add_interface_port avalon_master_1 master_byteenable_2 byteenable Output 4
add_interface_port avalon_master_1 master_readdata_2 readdata Input 32
add_interface_port avalon_master_1 master_readdatavalid_2 readdatavalid Input 1
add_interface_port avalon_master_1 master_writedata_2 writedata Output 32
add_interface_port avalon_master_1 master_waitrequest_2 waitrequest Input 1


# 
# connection point avalon_master_2
# 
add_interface avalon_master_2 avalon start
set_interface_property avalon_master_2 addressUnits SYMBOLS
set_interface_property avalon_master_2 associatedClock clock
set_interface_property avalon_master_2 associatedReset reset
set_interface_property avalon_master_2 bitsPerSymbol 8
set_interface_property avalon_master_2 burstOnBurstBoundariesOnly false
set_interface_property avalon_master_2 burstcountUnits WORDS
set_interface_property avalon_master_2 doStreamReads false
set_interface_property avalon_master_2 doStreamWrites false
set_interface_property avalon_master_2 holdTime 0
set_interface_property avalon_master_2 linewrapBursts false
set_interface_property avalon_master_2 maximumPendingReadTransactions 0
set_interface_property avalon_master_2 maximumPendingWriteTransactions 0
set_interface_property avalon_master_2 readLatency 0
set_interface_property avalon_master_2 readWaitTime 1
set_interface_property avalon_master_2 setupTime 0
set_interface_property avalon_master_2 timingUnits Cycles
set_interface_property avalon_master_2 writeWaitTime 0
set_interface_property avalon_master_2 ENABLED true
set_interface_property avalon_master_2 EXPORT_OF ""
set_interface_property avalon_master_2 PORT_NAME_MAP ""
set_interface_property avalon_master_2 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master_2 SVD_ADDRESS_GROUP ""

add_interface_port avalon_master_2 master_address_3 address Output 26
add_interface_port avalon_master_2 master_byteenable_3 byteenable Output 4
add_interface_port avalon_master_2 master_read_3 read Output 1
add_interface_port avalon_master_2 master_readdata_3 readdata Input 32
add_interface_port avalon_master_2 master_readdatavalid_3 readdatavalid Input 1
add_interface_port avalon_master_2 master_waitrequest_3 waitrequest Input 1
add_interface_port avalon_master_2 master_write_3 write Output 1
add_interface_port avalon_master_2 master_writedata_3 writedata Output 32


# 
# connection point avalon_slave
# 
add_interface avalon_slave avalon end
set_interface_property avalon_slave addressUnits SYMBOLS
set_interface_property avalon_slave associatedClock clock
set_interface_property avalon_slave associatedReset reset
set_interface_property avalon_slave bitsPerSymbol 8
set_interface_property avalon_slave burstOnBurstBoundariesOnly false
set_interface_property avalon_slave burstcountUnits WORDS
set_interface_property avalon_slave explicitAddressSpan 0
set_interface_property avalon_slave holdTime 0
set_interface_property avalon_slave linewrapBursts false
set_interface_property avalon_slave maximumPendingReadTransactions 0
set_interface_property avalon_slave maximumPendingWriteTransactions 0
set_interface_property avalon_slave readLatency 0
set_interface_property avalon_slave readWaitTime 1
set_interface_property avalon_slave setupTime 0
set_interface_property avalon_slave timingUnits Cycles
set_interface_property avalon_slave writeWaitTime 0
set_interface_property avalon_slave ENABLED true
set_interface_property avalon_slave EXPORT_OF ""
set_interface_property avalon_slave PORT_NAME_MAP ""
set_interface_property avalon_slave CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave address address Input 16
add_interface_port avalon_slave read read Input 1
add_interface_port avalon_slave readdata readdata Output 32
add_interface_port avalon_slave write write Input 1
add_interface_port avalon_slave writedata writedata Input 32
set_interface_assignment avalon_slave embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave embeddedsw.configuration.isPrintableDevice 0


# 
# connection point test
# 
add_interface test conduit end
set_interface_property test associatedClock clock
set_interface_property test associatedReset reset
set_interface_property test ENABLED true
set_interface_property test EXPORT_OF ""
set_interface_property test PORT_NAME_MAP ""
set_interface_property test CMSIS_SVD_VARIABLES ""
set_interface_property test SVD_ADDRESS_GROUP ""

add_interface_port test test test Output 1

