# TCL File Generated by Component Editor 18.1
# Tue Apr 23 21:59:28 EDT 2019
# DO NOT MODIFY


# 
# vga_unit "vga_unit" v1.0
#  2019.04.23.21:59:28
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module vga_unit
# 
set_module_property DESCRIPTION ""
set_module_property NAME vga_unit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME vga_unit
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL vga_unit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_unit.sv SYSTEM_VERILOG PATH vga_unit.sv TOP_LEVEL_FILE
add_fileset_file vga_unit_modules.sv SYSTEM_VERILOG PATH vga_unit_modules.sv
add_fileset_file bus_adapter.sv SYSTEM_VERILOG PATH bus_adapter.sv
add_fileset_file fifo.sv SYSTEM_VERILOG PATH fifo.sv
add_fileset_file decoder.sv SYSTEM_VERILOG PATH decoder.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL vga_unit
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file vga_unit.sv SYSTEM_VERILOG PATH vga_unit.sv
add_fileset_file vga_unit_modules.sv SYSTEM_VERILOG PATH vga_unit_modules.sv
add_fileset_file bus_adapter.sv SYSTEM_VERILOG PATH bus_adapter.sv
add_fileset_file fifo.sv SYSTEM_VERILOG PATH fifo.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset_n Input 1


# 
# connection point avalon_master
# 
add_interface avalon_master avalon start
set_interface_property avalon_master addressUnits SYMBOLS
set_interface_property avalon_master associatedClock clock
set_interface_property avalon_master associatedReset reset
set_interface_property avalon_master bitsPerSymbol 8
set_interface_property avalon_master burstOnBurstBoundariesOnly false
set_interface_property avalon_master burstcountUnits WORDS
set_interface_property avalon_master doStreamReads false
set_interface_property avalon_master doStreamWrites false
set_interface_property avalon_master holdTime 0
set_interface_property avalon_master linewrapBursts false
set_interface_property avalon_master maximumPendingReadTransactions 0
set_interface_property avalon_master maximumPendingWriteTransactions 0
set_interface_property avalon_master readLatency 0
set_interface_property avalon_master readWaitTime 1
set_interface_property avalon_master setupTime 0
set_interface_property avalon_master timingUnits Cycles
set_interface_property avalon_master writeWaitTime 0
set_interface_property avalon_master ENABLED true
set_interface_property avalon_master EXPORT_OF ""
set_interface_property avalon_master PORT_NAME_MAP ""
set_interface_property avalon_master CMSIS_SVD_VARIABLES ""
set_interface_property avalon_master SVD_ADDRESS_GROUP ""

add_interface_port avalon_master master_readdatavalid readdatavalid Input 1
add_interface_port avalon_master master_waitrequest waitrequest Input 1
add_interface_port avalon_master master_read read Output 1
add_interface_port avalon_master master_write write Output 1
add_interface_port avalon_master master_writedata writedata Output 16
add_interface_port avalon_master bus_data readdata Input 16
add_interface_port avalon_master master_address address Output 26
add_interface_port avalon_master master_byteenable byteenable Output 2


# 
# connection point frame_buffer
# 
add_interface frame_buffer conduit end
set_interface_property frame_buffer associatedClock clock
set_interface_property frame_buffer associatedReset ""
set_interface_property frame_buffer ENABLED true
set_interface_property frame_buffer EXPORT_OF ""
set_interface_property frame_buffer PORT_NAME_MAP ""
set_interface_property frame_buffer CMSIS_SVD_VARIABLES ""
set_interface_property frame_buffer SVD_ADDRESS_GROUP ""

add_interface_port frame_buffer frame_buffer_ptr frame_buffer_ptr Input 26


# 
# connection point VGA_display
# 
add_interface VGA_display conduit end
set_interface_property VGA_display associatedClock clock
set_interface_property VGA_display associatedReset reset
set_interface_property VGA_display ENABLED true
set_interface_property VGA_display EXPORT_OF ""
set_interface_property VGA_display PORT_NAME_MAP ""
set_interface_property VGA_display CMSIS_SVD_VARIABLES ""
set_interface_property VGA_display SVD_ADDRESS_GROUP ""

add_interface_port VGA_display VGA_B vga_b Output 8
add_interface_port VGA_display VGA_BLANK_n vga_blank Output 1
add_interface_port VGA_display VGA_CLK vga_clk Output 1
add_interface_port VGA_display VGA_G vga_g Output 8
add_interface_port VGA_display VGA_HS vga_hs Output 1
add_interface_port VGA_display VGA_R vga_r Output 8
add_interface_port VGA_display VGA_SYNC_n vga_sync Output 1
add_interface_port VGA_display VGA_VS vga_vs Output 1


# 
# connection point test
# 
add_interface test conduit end
set_interface_property test associatedClock clock
set_interface_property test associatedReset reset
set_interface_property test ENABLED true
set_interface_property test EXPORT_OF ""
set_interface_property test PORT_NAME_MAP ""
set_interface_property test CMSIS_SVD_VARIABLES ""
set_interface_property test SVD_ADDRESS_GROUP ""

add_interface_port test test_master_read master_read Output 1
add_interface_port test test_slave_read slave_read Output 1
add_interface_port test read_state hexout Output 7
add_interface_port test test_waitrequest waitrequest Output 1

