	system u0 (
		.clk_clk                       (<connected-to-clk_clk>),                       //      clk.clk
		.reset_reset_n                 (<connected-to-reset_reset_n>),                 //    reset.reset_n
		.hps_ddr3_mem_a                (<connected-to-hps_ddr3_mem_a>),                // hps_ddr3.mem_a
		.hps_ddr3_mem_ba               (<connected-to-hps_ddr3_mem_ba>),               //         .mem_ba
		.hps_ddr3_mem_ck               (<connected-to-hps_ddr3_mem_ck>),               //         .mem_ck
		.hps_ddr3_mem_ck_n             (<connected-to-hps_ddr3_mem_ck_n>),             //         .mem_ck_n
		.hps_ddr3_mem_cke              (<connected-to-hps_ddr3_mem_cke>),              //         .mem_cke
		.hps_ddr3_mem_cs_n             (<connected-to-hps_ddr3_mem_cs_n>),             //         .mem_cs_n
		.hps_ddr3_mem_ras_n            (<connected-to-hps_ddr3_mem_ras_n>),            //         .mem_ras_n
		.hps_ddr3_mem_cas_n            (<connected-to-hps_ddr3_mem_cas_n>),            //         .mem_cas_n
		.hps_ddr3_mem_we_n             (<connected-to-hps_ddr3_mem_we_n>),             //         .mem_we_n
		.hps_ddr3_mem_reset_n          (<connected-to-hps_ddr3_mem_reset_n>),          //         .mem_reset_n
		.hps_ddr3_mem_dq               (<connected-to-hps_ddr3_mem_dq>),               //         .mem_dq
		.hps_ddr3_mem_dqs              (<connected-to-hps_ddr3_mem_dqs>),              //         .mem_dqs
		.hps_ddr3_mem_dqs_n            (<connected-to-hps_ddr3_mem_dqs_n>),            //         .mem_dqs_n
		.hps_ddr3_mem_odt              (<connected-to-hps_ddr3_mem_odt>),              //         .mem_odt
		.hps_ddr3_mem_dm               (<connected-to-hps_ddr3_mem_dm>),               //         .mem_dm
		.hps_ddr3_oct_rzqin            (<connected-to-hps_ddr3_oct_rzqin>),            //         .oct_rzqin
		.hps_io_hps_io_sdio_inst_CMD   (<connected-to-hps_io_hps_io_sdio_inst_CMD>),   //   hps_io.hps_io_sdio_inst_CMD
		.hps_io_hps_io_sdio_inst_D0    (<connected-to-hps_io_hps_io_sdio_inst_D0>),    //         .hps_io_sdio_inst_D0
		.hps_io_hps_io_sdio_inst_D1    (<connected-to-hps_io_hps_io_sdio_inst_D1>),    //         .hps_io_sdio_inst_D1
		.hps_io_hps_io_sdio_inst_CLK   (<connected-to-hps_io_hps_io_sdio_inst_CLK>),   //         .hps_io_sdio_inst_CLK
		.hps_io_hps_io_sdio_inst_D2    (<connected-to-hps_io_hps_io_sdio_inst_D2>),    //         .hps_io_sdio_inst_D2
		.hps_io_hps_io_sdio_inst_D3    (<connected-to-hps_io_hps_io_sdio_inst_D3>),    //         .hps_io_sdio_inst_D3
		.hps_io_hps_io_usb1_inst_D0    (<connected-to-hps_io_hps_io_usb1_inst_D0>),    //         .hps_io_usb1_inst_D0
		.hps_io_hps_io_usb1_inst_D1    (<connected-to-hps_io_hps_io_usb1_inst_D1>),    //         .hps_io_usb1_inst_D1
		.hps_io_hps_io_usb1_inst_D2    (<connected-to-hps_io_hps_io_usb1_inst_D2>),    //         .hps_io_usb1_inst_D2
		.hps_io_hps_io_usb1_inst_D3    (<connected-to-hps_io_hps_io_usb1_inst_D3>),    //         .hps_io_usb1_inst_D3
		.hps_io_hps_io_usb1_inst_D4    (<connected-to-hps_io_hps_io_usb1_inst_D4>),    //         .hps_io_usb1_inst_D4
		.hps_io_hps_io_usb1_inst_D5    (<connected-to-hps_io_hps_io_usb1_inst_D5>),    //         .hps_io_usb1_inst_D5
		.hps_io_hps_io_usb1_inst_D6    (<connected-to-hps_io_hps_io_usb1_inst_D6>),    //         .hps_io_usb1_inst_D6
		.hps_io_hps_io_usb1_inst_D7    (<connected-to-hps_io_hps_io_usb1_inst_D7>),    //         .hps_io_usb1_inst_D7
		.hps_io_hps_io_usb1_inst_CLK   (<connected-to-hps_io_hps_io_usb1_inst_CLK>),   //         .hps_io_usb1_inst_CLK
		.hps_io_hps_io_usb1_inst_STP   (<connected-to-hps_io_hps_io_usb1_inst_STP>),   //         .hps_io_usb1_inst_STP
		.hps_io_hps_io_usb1_inst_DIR   (<connected-to-hps_io_hps_io_usb1_inst_DIR>),   //         .hps_io_usb1_inst_DIR
		.hps_io_hps_io_usb1_inst_NXT   (<connected-to-hps_io_hps_io_usb1_inst_NXT>),   //         .hps_io_usb1_inst_NXT
		.hps_io_hps_io_spim1_inst_CLK  (<connected-to-hps_io_hps_io_spim1_inst_CLK>),  //         .hps_io_spim1_inst_CLK
		.hps_io_hps_io_spim1_inst_MOSI (<connected-to-hps_io_hps_io_spim1_inst_MOSI>), //         .hps_io_spim1_inst_MOSI
		.hps_io_hps_io_spim1_inst_MISO (<connected-to-hps_io_hps_io_spim1_inst_MISO>), //         .hps_io_spim1_inst_MISO
		.hps_io_hps_io_spim1_inst_SS0  (<connected-to-hps_io_hps_io_spim1_inst_SS0>),  //         .hps_io_spim1_inst_SS0
		.hps_io_hps_io_uart0_inst_RX   (<connected-to-hps_io_hps_io_uart0_inst_RX>),   //         .hps_io_uart0_inst_RX
		.hps_io_hps_io_uart0_inst_TX   (<connected-to-hps_io_hps_io_uart0_inst_TX>),   //         .hps_io_uart0_inst_TX
		.hps_io_hps_io_i2c0_inst_SDA   (<connected-to-hps_io_hps_io_i2c0_inst_SDA>),   //         .hps_io_i2c0_inst_SDA
		.hps_io_hps_io_i2c0_inst_SCL   (<connected-to-hps_io_hps_io_i2c0_inst_SCL>),   //         .hps_io_i2c0_inst_SCL
		.hps_io_hps_io_i2c1_inst_SDA   (<connected-to-hps_io_hps_io_i2c1_inst_SDA>),   //         .hps_io_i2c1_inst_SDA
		.hps_io_hps_io_i2c1_inst_SCL   (<connected-to-hps_io_hps_io_i2c1_inst_SCL>),   //         .hps_io_i2c1_inst_SCL
		.sdram_addr                    (<connected-to-sdram_addr>),                    //    sdram.addr
		.sdram_ba                      (<connected-to-sdram_ba>),                      //         .ba
		.sdram_cas_n                   (<connected-to-sdram_cas_n>),                   //         .cas_n
		.sdram_cke                     (<connected-to-sdram_cke>),                     //         .cke
		.sdram_cs_n                    (<connected-to-sdram_cs_n>),                    //         .cs_n
		.sdram_dq                      (<connected-to-sdram_dq>),                      //         .dq
		.sdram_dqm                     (<connected-to-sdram_dqm>),                     //         .dqm
		.sdram_ras_n                   (<connected-to-sdram_ras_n>),                   //         .ras_n
		.sdram_we_n                    (<connected-to-sdram_we_n>)                     //         .we_n
	);

